### ISSUE TITLE
API Call via HTTPS

### ISSUE THREAD

**Issue by obstschale** [sharpfuryz/zoommy_wordpress#1]
Hey,

I just bought Zoommy and I like it so far. Now I wanted to test your WP plugin. Unfortunately, I cannot use it because your plugin is using HTTP only to call your API but I am using HTTPS. Please use HTTPS! I actually don't want that my licencse key is transmitted via HTTP.

![captura_de_pantalla_2016-02-06_a_las_12_35_35](https://cloud.githubusercontent.com/assets/1058710/12866472/ad3afe0a-ccce-11e5-9966-767fc7e73294.jpg)

**Comment by sharpfuryz** [comment]
Our API is fully supported by https, so with next release - plugin would be fixed.

**Comment by obstschale** [comment]
:+1: Nice thx.
